export const projects = [
  {
    title: 'Track & Trace System',
    description: 'Led delivery governance for a nationwide program where cost control, vendor coordination, and forecast accuracy mattered most. The effort reduced budget variance to 22.5% under plan and delivered PKR 103M+ in savings while keeping implementation aligned to public-sector compliance and delivery milestones.',
    impact: 'PKR 103M+ savings and 22.5% under plan',
    category: 'Public sector',
    caseStudy: '/case-studies/track-trace.html',
    image: '/images/8.PNG',
    tags: ['Budget Control', 'Forecasting', 'PMO'],
    website: 'https://www.fbr.gov.pk/introduction-track-and-trace/152962/152963',
    id: 0,
  },
  {
    title: 'CDA Smart Parking Digitization',
    description: 'Coordinated business requirements, sprint execution, UAT, and release readiness across a fast-moving digital parking program. I helped maintain delivery momentum while aligning stakeholder expectations, risk review, and rollout dependencies.',
    impact: 'Delivery alignment through UAT and rollout readiness',
    category: 'Public sector',
    caseStudy: '/case-studies/cda-smart-parking.html',
    image: '/images/6.jpg',
    tags: ['Agile Delivery', 'RAID', 'UAT'],
    website: 'https://www.realparkanpr.com/revolutionizing-parking-in-pakistan-new-parking-management-system-coming-soon-to-islamabad2.html',
    id: 1,
  },
  {
    title: 'Thunder',
    client: 'Telenor Pakistan',
    sector: 'Telecom',
    description: 'Product engineering for Telenor Pakistan’s Thunder platform, using live tower data and predictive insights to support proactive maintenance at national scale.',
    impact: 'Published project results: 60% lower operating costs',
    category: 'Digital platforms',
    caseStudy: '/case-studies/thunder-energy.html',
    tags: ['Tower telemetry', 'Predictive analytics', 'Maintenance'],
    website: 'https://www.telenor.com.pk/',
    id: 2,
  },
   {
    title: 'Digital workflow for spectrum allocation',
    client: 'Frequency Allocation Board',
    sector: 'Telecom',
    description: 'A digital application portal and review workflow replacing paper-based spectrum allocation processes for Pakistan’s telecom regulator.',
    impact: 'Online submissions and trackable review workflows',
    category: 'Public sector',
    caseStudy: '/case-studies/frequency-allocation-board.html',
    image: '/images/9.png',
    tags: ['Online portal', 'Workflow management', 'Public sector'],
    website: 'https://portal.fab.gov.pk/',
    id: 3,
  },
{
    title: 'Taggy Marketplace Platform',
    description: 'Managed concurrent delivery of the Taggy marketplace platform, coordinating client communication, task assignment, and progress tracking across parallel workstreams. Structured Trello boards to keep cross-functional teams aligned on sprints and deadlines, and produced user manuals to support a smooth handover and adoption for end users.',
    impact: 'Clearer sprint coordination and smoother handover',
    category: 'Digital platforms',
    caseStudy: '/case-studies/taggy-marketplace.html',
    image: '/images/10.png',
    tags: ['Client Coordination', 'Trello', 'Sprint Tracking', 'Documentation'],
    website: 'https://taggy.ae/',
    id: 4,
  },
{
    title: 'APC Admin Portal',
    description: 'Served as primary client point of contact for the Aviation Professionals Club (APC) Admin Portal, translating requirements into actionable development tasks and providing regular status updates. Authored a comprehensive technical user manual covering all portal modules, ensuring smooth handover and adoption post-delivery.',
    impact: 'Complete module documentation for handover and adoption',
    category: 'Digital platforms',
    caseStudy: '/case-studies/apc-admin-portal.html',
    image: '/images/11.png',
    tags: ['Requirements', 'Client Communication', 'Documentation', 'UAT'],
    website: 'https://apc.ae/pages/index',
    id: 5,
  },
  {
    title: 'Serverless commerce platform',
    client: 'PrettyLittleThing',
    sector: 'E-commerce',
    description: 'A serverless re-platforming program designed to help a global fashion retailer scale beyond the limits of its existing commerce stack.',
    impact: 'Published outcomes: 600k daily customers · 60% lower infrastructure costs',
    category: 'E-commerce',
    caseStudy: '/case-studies/prettylittlething-ecommerce.html',
    image: '/images/12.png',
    tags: ['Serverless migration', 'AWS', 'Release coordination'],
    website: 'https://www.prettylittlething.eu/',
    id: 6,
  },
{
    title: 'Unified returns platform',
    client: 'Boohoo Group',
    sector: 'E-commerce',
    description: 'A bespoke returns platform bringing brands together through a unified flow, with integrations reaching order, SKU, and warehouse systems.',
    impact: 'Unified returns operations across multiple brands',
    category: 'E-commerce',
    caseStudy: '/case-studies/boohoo-ecommerce.html',
    image: '/images/13.png',
    tags: ['AWS serverless', 'Commerce integration', 'Delivery coordination'],
    website: 'https://eu.boohoo.com/',
    id: 7,
  },

];

export const TimeLineData = [
  { year: '2019–2021', text: 'Site Engineer (PMO) at Al Rehman Enterprises, coordinating construction delivery, schedules, budgets, and stakeholder resolution.', },
  { year: '2022', text: 'Business Development Officer at Mobiserve Pakistan, building client proposals and targeted growth campaigns.', },
  { year: '2023–2024', text: 'Progressed from Junior Project Coordinator to Associate Project Manager at SOFTOO, leading Agile delivery for enterprise platforms.', },
  { year: '2024–2026', text: 'Project Planning and Control Engineer at AJCL, managing a PKR 700M+ portfolio across 150+ sites with PMO discipline and Power BI visibility.', },
  { year: '2026–Present', text: 'Project Manager at Sigma Digital Solutions, leading concurrent software delivery for Taggy, APC, and Premier Online.', },
];