export const projects = [
  {
    title: 'Thunder',
    client: 'Telenor Pakistan',
    sector: 'Telecom',
    description: 'Product engineering for Telenor Pakistan’s Thunder platform, using live tower data and predictive insights to support proactive maintenance at national scale.',
    impact: 'Published project results: 60% lower operating costs',
    category: 'Digital platforms',
    projectTypes: ['Enterprise PM', 'Digital & Software', 'Consulting'],
    caseStudy: '/case-studies/thunder-energy.html',
    tags: ['Tower telemetry', 'Predictive analytics', 'Maintenance'],
    website: 'https://www.thunderenergy.ai/',
    id: 2,
  },
  {
    title: 'Digital workflow for spectrum allocation',
    client: 'Frequency Allocation Board',
    sector: 'Telecom',
    description: 'A digital application portal and review workflow replacing paper-based spectrum allocation processes for Pakistan’s telecom regulator.',
    impact: 'Online submissions and trackable review workflows',
    category: 'Public sector',
    projectTypes: ['Enterprise PM', 'Digital & Software', 'Consulting'],
    caseStudy: '/case-studies/frequency-allocation-board.html',
    image: '/images/9.png',
    tags: ['Online portal', 'Workflow management', 'Public sector'],
    website: 'https://portal.fab.gov.pk/',
    id: 3,
  },
  {
    title: 'Boohoo Group returns platform',
    client: 'Boohoo Group',
    sector: 'E-commerce',
    description: 'A bespoke returns platform bringing brands together through a unified flow, integrating order and SKU details with warehouse systems.',
    impact: 'Unified returns operations across multiple brands',
    category: 'E-commerce',
    projectTypes: ['Enterprise PM', 'Digital & Software', 'Consulting'],
    caseStudy: '/case-studies/boohoo-ecommerce.html',
    image: '/images/13.png',
    tags: ['AWS serverless', 'Commerce integration', 'Delivery coordination'],
    website: 'https://eu.boohoo.com/',
    id: 7,
  },
  {
    title: 'PrettyLittleThing serverless migration',
    client: 'PrettyLittleThing',
    sector: 'E-commerce',
    description: 'A serverless re-platforming program modernizing the commerce stack for scale and resilience at a global fashion retailer.',
    impact: 'Published outcomes: 600k daily customers · 60% lower infrastructure costs',
    category: 'E-commerce',
    projectTypes: ['Enterprise PM', 'Digital & Software', 'Consulting'],
    caseStudy: '/case-studies/prettylittlething-ecommerce.html',
    image: '/images/12.png',
    tags: ['Serverless migration', 'AWS', 'Release coordination'],
    website: 'https://www.prettylittlething.eu/',
    id: 6,
  },
  {
    title: 'Track & Trace System',
    client: 'Federal Board of Revenue',
    sector: 'Public sector',
    description: 'A nationwide traceability program using unique identification marks to support electronic monitoring of production and sales in notified sectors.',
    impact: 'Portfolio delivery reported PKR 103M+ savings and 22.5% under plan',
    category: 'Public sector',
    projectTypes: ['Enterprise PM', 'Consulting'],
    caseStudy: '/case-studies/track-trace.html',
    image: '/images/8.PNG',
    tags: ['Budget control', 'Forecasting', 'PMO'],
    website: 'https://www.fbr.gov.pk/introduction-track-and-trace/152962/152963',
    id: 0,
  },
  {
    title: 'CDA Smart Parking Digitization',
    client: 'Capital Development Authority',
    sector: 'Public sector',
    description: 'An announced APNR-based parking management system for Islamabad, developed with CDA to digitize parking operations.',
    impact: 'Coordinated delivery through UAT and rollout readiness',
    category: 'Public sector',
    projectTypes: ['Digital & Software', 'Consulting'],
    caseStudy: '/case-studies/cda-smart-parking.html',
    image: '/images/6.jpg',
    tags: ['Agile delivery', 'RAID', 'UAT'],
    website: 'https://www.realparkanpr.com/revolutionizing-parking-in-pakistan-new-parking-management-system-coming-soon-to-islamabad2.html',
    id: 1,
  },
  {
    title: 'Taggy Marketplace Platform',
    client: 'Taggy',
    sector: 'Digital platforms',
    description: 'A fashion-resale marketplace where shoppers can browse listings and sellers can list items, supported by discovery tools such as image search and auto-tagging.',
    impact: 'Coordinated parallel delivery workstreams and handover',
    category: 'Digital platforms',
    projectTypes: ['Digital & Software', 'Consulting'],
    caseStudy: '/case-studies/taggy-marketplace.html',
    image: '/images/10.png',
    tags: ['Marketplace', 'Client coordination', 'Documentation'],
    website: 'https://taggy.ae/',
    id: 4,
  },
  {
    title: 'APC Admin Portal',
    client: 'Aviation Professionals Club',
    sector: 'Digital platforms',
    description: 'A member-facing digital experience for an aviation-professional benefits club, connecting eligible UAE aviation staff with partner offers and club services.',
    impact: 'Module documentation prepared for handover and adoption',
    category: 'Digital platforms',
    projectTypes: ['Digital & Software', 'Consulting'],
    caseStudy: '/case-studies/apc-admin-portal.html',
    image: '/images/11.png',
    tags: ['Requirements', 'Client communication', 'Documentation'],
    website: 'https://apc.ae/pages/index',
    id: 5,
  },
];

export const TimeLineData = [
  { year: '2019–2021', text: 'Site Engineer (PMO) at Al Rehman Enterprises, coordinating construction delivery, schedules, budgets, and stakeholder resolution.', },
  { year: '2022', text: 'Business Development Officer at Mobiserve Pakistan, building client proposals and targeted growth campaigns.', },
  { year: '2023–2024', text: 'Progressed from Junior Project Coordinator to Associate Project Manager at SOFTOO, leading Agile delivery for enterprise platforms.', },
  { year: '2024–2026', text: 'Project Planning and Control Engineer at AJCL, managing a PKR 700M+ portfolio across 150+ sites with PMO discipline and Power BI visibility.', },
  { year: '2026–Present', text: 'Project Manager at Sigma Digital Solutions, leading concurrent software delivery for Taggy, APC, and Premier Online.', },
];