export const projects = [
  {
    title: 'Track & Trace System',
    description: 'Led delivery governance for a nationwide program where cost control, vendor coordination, and forecast accuracy mattered most. The effort reduced budget variance to 22.5% under plan and delivered PKR 103M+ in savings while keeping implementation aligned to public-sector compliance and delivery milestones.',
    impact: 'PKR 103M+ savings and 22.5% under plan',
    image: '/images/8.png',
    tags: ['Budget Control', 'Forecasting', 'PMO'],
    website: 'https://www.fbr.gov.pk/introduction-track-and-trace/152962/152963',
    id: 0,
  },
  {
    title: 'CDA Smart Parking Digitization',
    description: 'Coordinated business requirements, sprint execution, UAT, and release readiness across a fast-moving digital parking program. I helped maintain delivery momentum while aligning stakeholder expectations, risk review, and rollout dependencies.',
    impact: 'Delivery alignment through UAT and rollout readiness',
    image: '/images/6.jpg',
    tags: ['Agile Delivery', 'RAID', 'UAT'],
    website: 'https://www.realparkanpr.com/revolutionizing-parking-in-pakistan-new-parking-management-system-coming-soon-to-islamabad2.html',
    id: 1,
  },
  {
    title: 'Thunder Energy Analytics',
    description: 'Owned delivery end-to-end for a data and analytics platform, adapting scope and priorities as client needs evolved. The result was a production-ready analytics capability that supported clearer reporting and faster decision-making for stakeholders.',
    impact: 'Production-ready analytics capability',
    image: '/images/5.png',
    tags: ['Stakeholders', 'Requirements', 'Release'],
    website: 'https://www.thunderenergy.ai/',
    id: 2,
  },
   {
    title: 'Frequency Allocation Board',
    description: 'Supported task coordination and documentation for a public-sector website project, helping maintain alignment across stakeholders and keep progress visible. The work improved transparency, reduced delivery ambiguity, and supported tighter execution tracking.',
    impact: 'Improved transparency and execution tracking',
    image: '/images/9.png',
    tags: ['Stakeholders', 'Requirements', 'Documentation', 'Scrumban' ],
    website: 'https://portal.fab.gov.pk/',
    id: 3,
  },
{
    title: 'Taggy Marketplace Platform',
    description: 'Managed concurrent delivery of the Taggy marketplace platform, coordinating client communication, task assignment, and progress tracking across parallel workstreams. Structured Trello boards to keep cross-functional teams aligned on sprints and deadlines, and produced user manuals to support a smooth handover and adoption for end users.',
    impact: 'Clearer sprint coordination and smoother handover',
    image: '/images/10.png',
    tags: ['Client Coordination', 'Trello', 'Sprint Tracking', 'Documentation'],
    website: 'https://taggy.ae/',
    id: 4,
  },
{
    title: 'APC Admin Portal',
    description: 'Served as primary client point of contact for the Aviation Professionals Club (APC) Admin Portal, translating requirements into actionable development tasks and providing regular status updates. Authored a comprehensive technical user manual covering all portal modules, ensuring smooth handover and adoption post-delivery.',
    impact: 'Complete module documentation for handover and adoption',
    image: '/images/11.png',
    tags: ['Requirements', 'Client Communication', 'Documentation', 'UAT'],
    website: 'https://apc.ae/pages/index',
    id: 5,
  },
  {
    title: 'PrettyLittleThing E-Commerce Platform',
    description: 'Coordinated weekly delivery meetings between business stakeholders and technical teams for the PrettyLittleThing e-commerce platform, keeping releases aligned across development, QA, and infrastructure. Streamlined project documentation to improve accuracy of milestone tracking, which reduced reporting errors and strengthened stakeholder visibility into release progress.',
    impact: 'Improved transparency and execution tracking',
    image: '/images/12.png',
    tags: ['Sprint Coordination', 'Stakeholder Communication', 'Documentation', 'QA'],
    website: 'https://www.prettylittlething.eu/',
    id: 6,
  },
{
    title: 'Boohoo E-Commerce Platform',
    description: 'Supported delivery coordination for the Boohoo e-commerce platform, aligning business stakeholders and technical teams through structured weekly delivery meetings. Improved documentation accuracy across the release cycle, cutting reporting errors and tightening cross-team alignment on milestones.',
    impact: 'Reduced reporting errors and tightened cross-team alignment',
    image: '/images/13.png',
    tags: ['Sprint Coordination', 'Stakeholder Communication', 'Documentation', 'QA'],
    website: 'https://eu.boohoo.com/',
    id: 7,
  },

];

export const TimeLineData = [
  { year: '2019–2021', text: 'Site Engineer (PMO) at Al Rehman Enterprises, coordinating construction delivery, schedules, budgets, and stakeholder resolution.', },
  { year: '2022', text: 'Business Development Officer at Mobiserve Pakistan, building client proposals and targeted growth campaigns.', },
  { year: '2023–2024', text: 'Progressed from Junior Project Coordinator to Associate Project Manager at SOFTOO, leading Agile delivery for enterprise platforms.', },
  { year: '2024–2026', text: 'Project Planning and Control Engineer at AJCL, managing a PKR 700M+ portfolio across 150+ sites with PMO discipline and Power BI visibility.', },
  { year: '2026–Present', text: 'Project Manager at Sigma Digital Solutions, leading concurrent software delivery for Taggy, APC, and Premier Online.', },
];